# https://github.com/xtoys
#
# Description: Build DockerImages using GitHub Actions
#

name: Chatie Bot

on:
  push:
    tags:
      - "*"

env:
    # github.repository as <account>/<repo>
    IMAGE_NAME: ${{ github.repository }}
    IMAGE_PLATFORM: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker Buildx

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and Publish image
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: ${{ env.IMAGE_PLATFORM }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
